export async function generateGroqContent(
  prompt: string,
  systemPrompt: string = "You are an expert LinkedIn ghostwriter and content strategist.",
  model: string = "llama-3.3-70b-versatile"
): Promise<string> {
  const apiKey = process.env.GROQ_API_KEY

  if (!apiKey) {
    throw new Error('Groq API key is not configured.')
  }

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: prompt }
      ],
      temperature: 0.75,
      max_tokens: 2048,  // Increased from 1024 to allow long-form content
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    console.error('Groq API Error:', errorText)
    throw new Error(`Groq API error: ${response.status} - ${errorText}`)
  }

  const data = await response.json()
  const content = data.choices[0]?.message?.content

  if (!content) {
    throw new Error('No content generated by Groq')
  }

  return content.trim()
}

/**
 * Generate LinkedIn post using Groq - returns structured post with title
 */
export async function generateLinkedInPost(
  topic: string,
  style: string,
  tone: string,
  length: number
): Promise<string> {
  const lengthGuide: Record<number, string> = {
    1: 'very short (100-150 words)',
    2: 'short (150-250 words)',
    3: 'medium (300-500 words, 8-12 paragraphs/bullet points)',
    4: 'long (500-700 words, 12-18 paragraphs/bullet points)',
    5: 'very long (700-1000 words, detailed with multiple sections)',
  }

  const systemPrompt = `You are an expert LinkedIn ghostwriter and content strategist. 
Your posts go viral because they are detailed, insightful, and genuinely valuable.
You always write posts that are AT LEAST the minimum word count specified.
You NEVER truncate or cut content short.`

  const prompt = `Write a ${lengthGuide[length] || 'medium (300-500 words)'} LinkedIn post about: "${topic}"

STRICT FORMAT (follow exactly):
TITLE: [Write a punchy, attention-grabbing title in 5-10 words]

[FULL POST CONTENT - write the complete post below]

Requirements:
- Writing style: ${style}
- Tone: ${tone}  
- Start with a powerful hook sentence that stops the scroll
- Use SHORT paragraphs (1-3 sentences max each) for readability
- Add relevant emojis naturally throughout (not just at the start)
- Include 3-5 bullet points or numbered insights in the middle
- End with a strong call-to-action question to drive comments
- Add 3-5 relevant hashtags at the very end
- Write the COMPLETE post — do not cut it short
- Make it genuinely insightful and valuable, not generic

Return ONLY the TITLE line followed by the post content. No extra commentary.`

  return generateGroqContent(prompt, systemPrompt)
}

/**
 * Generate multiple post variations
 */
export async function generatePostVariations(
  topic: string,
  style: string,
  tone: string,
  length: number,
  count: number = 3
): Promise<string[]> {
  const promises = []
  for (let i = 0; i < count; i++) {
    promises.push(generateLinkedInPost(topic, style, tone, length))
  }
  return Promise.all(promises)
}

/**
 * Generate LinkedIn post from template
 */
export async function generateFromTemplate(
  template: {
    name: string
    template: string
    variables?: string[]
  },
  tone: string,
  userInput?: { topics?: string[] }
): Promise<string> {
  const systemPrompt = `You are an expert LinkedIn ghostwriter. I have a proven LinkedIn post template that I want you to fill in with engaging content. Write detailed, complete content — never truncate.`

  const prompt = `Template Name: ${template.name}
Tone: ${tone}

Template Structure:
${template.template}

Instructions:
- Use this EXACT template structure as your framework
- Fill in the placeholders/variables with compelling, specific content
${userInput?.topics && userInput.topics.length > 0 ? `- Focus the content on these topics: ${userInput.topics.join(', ')}` : ''}
- Maintain the ${tone} tone throughout
- Keep the same formatting, line breaks, and structure as the template
- Make it authentic, engaging, and COMPLETE — do not cut it short
- Use emojis where appropriate (don't overdo it)
- Ensure the content flows naturally and is at least 300 words

TITLE: [Write a punchy title for this post]

Return the TITLE line first, then the full post content. No additional commentary.`

  return generateGroqContent(prompt, systemPrompt)
}

/**
 * Generate multiple variations from template
 */
export async function generateTemplateVariations(
  template: {
    name: string
    template: string
    variables?: string[]
  },
  tone: string,
  count: number = 3,
  userInput?: { topics?: string[] }
): Promise<string[]> {
  const promises = []
  for (let i = 0; i < count; i++) {
    promises.push(generateFromTemplate(template, tone, userInput))
  }
  return Promise.all(promises)
}
